import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Image from 'next/image';
import URLProvider from './context/URLProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Image
          src='/cubes.svg'
          className='relative -z-10'
          layout='fill'
          alt='backgound-image'
        />
        <Image
          src='/swirl.svg'
          className='relative -z-20'
          layout='fill'
          alt='backgound-image'
        />
        <URLProvider>{children}</URLProvider>
      </body>
    </html>
  );
}
